name: STM32 CubeIDE Build Pipeline

# This specifies when to trigger the workflow (e.g., on pushes or pull requests to the `main` branch)
on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install ARM Toolchain
      - name: Set up ARM toolchain
        run: sudo apt-get install gcc-arm-none-eabi

      # Step 3: Build the CubeIDE project using the Makefile
      - name: Build STM32 CubeIDE project
        run: |
          cd STM32-CPU-FAN-Controller-With-RPM-Monitoring/Debug
          make -j$(nproc)

      # Optional: Upload the build artifact (firmware file, e.g., .bin, .elf)
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: STM32-CPU-FAN-Controller-With-RPM-Monitoring/Debug/firmware.elf
